-- Safe Baseline Migration Assertion for Existing LogiMarket Database Structure
-- This file was originally generated by Drizzle Kit and modified to perform structure checks.

DO $$
DECLARE
  v_count integer;
BEGIN
  -- 1. Sprawdzenie istnienia legacy tables
  IF NOT EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'partners') THEN
    RAISE EXCEPTION 'Legacy table public.partners is missing' USING ERRCODE = 'check_violation';
  END IF;
  IF NOT EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'categories') THEN
    RAISE EXCEPTION 'Legacy table public.categories is missing' USING ERRCODE = 'check_violation';
  END IF;
  IF NOT EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'offers') THEN
    RAISE EXCEPTION 'Legacy table public.offers is missing' USING ERRCODE = 'check_violation';
  END IF;
  IF NOT EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'clicks') THEN
    RAISE EXCEPTION 'Legacy table public.clicks is missing' USING ERRCODE = 'check_violation';
  END IF;
  IF NOT EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'orders') THEN
    RAISE EXCEPTION 'Legacy table public.orders is missing' USING ERRCODE = 'check_violation';
  END IF;
  IF NOT EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'order_items') THEN
    RAISE EXCEPTION 'Legacy table public.order_items is missing' USING ERRCODE = 'check_violation';
  END IF;

  -- 2. Sprawdzenie kolumny public.offers.id
  SELECT count(*) INTO v_count
  FROM information_schema.columns
  WHERE table_schema = 'public'
    AND table_name = 'offers'
    AND column_name = 'id'
    AND data_type = 'bigint'
    AND is_nullable = 'NO';

  IF v_count = 0 THEN
    RAISE EXCEPTION 'Column public.offers.id must exist, be of type bigint, and be NOT NULL' USING ERRCODE = 'check_violation';
  END IF;

  -- 3. Sprawdzenie PK na public.offers.id
  SELECT count(*) INTO v_count
  FROM information_schema.table_constraints tc
  JOIN information_schema.key_column_usage kcu
    ON tc.constraint_name = kcu.constraint_name
    AND tc.table_schema = kcu.table_schema
  WHERE tc.table_schema = 'public'
    AND tc.table_name = 'offers'
    AND tc.constraint_type = 'PRIMARY KEY'
    AND kcu.column_name = 'id';

  IF v_count = 0 THEN
    RAISE EXCEPTION 'Table public.offers must have a PRIMARY KEY constraint on id' USING ERRCODE = 'check_violation';
  END IF;

  -- 4. Sprawdzenie braku częściowej instalacji nowych obiektów
  IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name IN (
    'attribute_definitions',
    'controlled_option_values',
    'offer_attribute_values',
    'offer_attribute_option_values',
    'migration_batches',
    'migration_source_entries',
    'migration_oav_targets',
    'migration_oaov_targets'
  )) OR EXISTS (
    SELECT FROM information_schema.schemata WHERE schema_name = 'migration_private'
  ) THEN
    RAISE EXCEPTION 'PARTIAL FACET ARCHITECTURE DETECTED. Legacy database contains existing faceted search tables or schema.' USING ERRCODE = 'check_violation';
  END IF;

END $$;
